name: Its Time for VHAGAR

on: [push]

jobs:
  To_View:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello to our guys
      run: echo "Hello Learner Sri Hari"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: View File
      run: ls -la

    - name: View File Content
      run: cat readme

    - name: Istall ASCII Generator
      run: |
        sudo apt-get update
        sudo apt-get install -y figlet cowsay lolcat
        chmod +x scripts/dragon_chaos.sh

    - name: Generate ASCII
      run:  bash scripts/dragon_chaos.sh